### PR TITLE
Fixes for 3DCM020200r015 firmware

### LINKED ISSUE #288: Temperature type conflict - Unknown error occurred - haos
Here is the continuation of the previous issue created in https://github.com/home-assistant/core/issues/125336.

### The problem

Hi,

When I try to add the `SFR Box` integration to my haos, I have the following error:

I've got this on the api webpage : `http://a.b.c.d/api/1.0/?method=system.getInfo`
```html
<rsp stat="ok" version="1.0">
<script id="nimlmejbmnecnaghgmbahmbaddhjbecg"/>
<script/>
<script/>
<system product_id="ALGD1-UBE-r0" serial_number="MU1B01140006020043" mac_addr="***hidden***" net_mode="router" net_infra="fttb" uptime="1564075" version_mainfirmware="3DCM020200r015" version_rescuefirmware="3DCM020200r015" version_bootloader="3.00" version_dsldriver="" current_datetime="20240905131928" refclient="" idur="RNCUAOL" alimvoltage="12251" temperature="57.4"/>
</rsp>
```

### Anything in the logs that might be useful for us?

```txt
2024-09-05 13:09:08.791 DEBUG (MainThread) [sfrbox_api.bridge] HTTP Response: GET http://192.168.1.1/api/1.0/?method=system.getInfo "HTTP/1.1 200 Ok" <?xml version="1.0" encoding="UTF-8"?><rsp stat="ok" version="1.0"><system product_id="ALGD1-UBE-r0" serial_number="MU1B01140006020043" mac_addr="***hidden***" net_mode="router" net_infra="fttb" uptime="1563441" version_mainfirmware="3DCM020200r015" version_rescuefirmware="3DCM020200r015" version_bootloader="3.00" version_dsldriver="" current_datetime="20240905130854" refclient="" idur="RNCUAOL" alimvoltage="12251" temperature="57.5" />
</rsp>
2024-09-05 13:09:08.792 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
result: _FlowResultT = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sfr_box/config_flow.py", line 50, in async_step_user
system_info = await box.system_get_info()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/sfrbox_api/bridge.py", line 179, in system_get_info
return SystemInfo(**xml_response.attrib) # type: ignore[arg-type]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "pydantic/dataclasses.py", line 332, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
File "pydantic/dataclasses.py", line 447, in pydantic.dataclasses._dataclass_validate_values
pydantic.error_wrappers.ValidationError: 1 validation error for SystemInfo
temperature
value is not a valid integer (type=type_error.integer)
```

### Additional information

The request to `http://a.b.c.d/api/1.0/?method=auth.getToken` seems to give me a correct token:

```xml
<rsp stat="ok" version="1.0">
<script id="nimlmejbmnecnaghgmbahmbaddhjbecg"/>
<script/>
<script/>
<auth token="***hidden***" method="all"/>
</rsp>
```

### PR DESCRIPTION
**Pull request by epenet**
Should fix #288

cc @AlexT59

### CODE REVIEW

**Comment by epenet** [comment]
@AlexT59 are you able to run some extra tests to see if SFR Box v8 needs further tweaks?

**Comment by AlexT59** [comment]
I tried to run the `example.py`, the first step with the bug of the temperature seems fixed but I got the following exeption:

```
> python3 src/example.py
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/home/dev/.local/lib/python3.10/site-packages/certifi/cacert.pem'
DEBUG:httpcore.connection:connect_tcp.started host='192.168.1.1' port=80 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7f685724a7a0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'Ok', [(b'Server', b'micro_httpd'), (b'Cache-Control', b'no-cache'), (b'Date', b'Thu, 05 Sep 2024 14:18:00 GMT'), (b'Content-Type', b'text/xml; charset=utf-8'), (b'X-XSS-Protection', b'1; mode=block'), (b'X-Frame-Options', b'deny'), (b'Connection', b'close')])
INFO:httpx:HTTP Request: GET http://192.168.1.1/api/1.0/?method=system.getInfo "HTTP/1.1 200 Ok"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:sfrbox_api.bridge:HTTP Response: GET http://192.168.1.1/api/1.0/?method=system.getInfo "HTTP/1.1 200 Ok" <?xml version="1.0" encoding="UTF-8"?><rsp stat="ok" version="1.0"><system product_id="ALGD1-UBE-r0" serial_number="MU1B01140006020043" mac_addr="***hidden***" net_mode="router" net_infra="fttb" uptime="1574768" version_mainfirmware="3DCM020200r015" version_rescuefirmware="3DCM020200r015" version_bootloader="3.00" version_dsldriver="" current_datetime="20240905161741" refclient="" idur="RNCUAOL" alimvoltage="12251" temperature="59.0" />
</rsp>

SystemInfo(product_id='ALGD1-UBE-r0', mac_addr='***hidden***', net_mode='router', net_infra='fttb', uptime=1574768, version_mainfirmware='3DCM020200r015', version_rescuefirmware='3DCM020200r015', version_bootloader='3.00', version_dsldriver='', current_datetime='20240905161741', refclient='', idur='RNCUAOL', alimvoltage=12251, temperature=59.0, serial_number='MU1B01140006020043')
DEBUG:httpcore.connection:connect_tcp.started host='192.168.1.1' port=80 local_address=None timeout=5.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7f6857249030>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'Ok', [(b'Server', b'micro_httpd'), (b'Cache-Control', b'no-cache'), (b'Date', b'Thu, 05 Sep 2024 14:18:00 GMT'), (b'Content-Type', b'text/xml; charset=utf-8'), (b'X-XSS-Protection', b'1; mode=block'), (b'X-Frame-Options', b'deny'), (b'Connection', b'close')])
INFO:httpx:HTTP Request: GET http://192.168.1.1/api/1.0/?method=dsl.getInfo "HTTP/1.1 200 Ok"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:sfrbox_api.bridge:HTTP Response: GET http://192.168.1.1/api/1.0/?method=dsl.getInfo "HTTP/1.1 200 Ok" <?xml version="1.0" encoding="UTF-8"?><rsp stat="ok" version="1.0"><dsl linemode="G.DMT" uptime="4857" counter="1" crc="0" status="up" noise_down="4.5" noise_up="4.2" attenuation_down="3.2" attenuation_up="5.2" rate_down="8000" rate_up="800"
</firewall>
</rsp>

Traceback (most recent call last):
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1713, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 2, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/GIT/sfrbox-api/src/sfrbox_api/bridge.py", line 111, in _check_response
    element: XmlElement = DefusedElementTree.fromstring(response.text)
  File "/home/dev/.local/lib/python3.10/site-packages/defusedxml/common.py", line 126, in fromstring
    parser.feed(text)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1715, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1622, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dev/GIT/sfrbox-api/src/example.py", line 33, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/dev/GIT/sfrbox-api/src/example.py", line 23, in main
    print(await box.dsl_get_info())
  File "/home/dev/GIT/sfrbox-api/src/sfrbox_api/bridge.py", line 168, in dsl_get_info
    xml_response = await self._send_get("dsl", "getInfo")
  File "/home/dev/GIT/sfrbox-api/src/sfrbox_api/bridge.py", line 51, in wrapper
    return await func(*args, **kwargs)
  File "/home/dev/GIT/sfrbox-api/src/sfrbox_api/bridge.py", line 143, in _send_get
    element = self._check_response(response)
  File "/home/dev/GIT/sfrbox-api/src/sfrbox_api/bridge.py", line 113, in _check_response
    raise SFRBoxError(f"Failed to parse response: {response.text}") from exc
sfrbox_api.exceptions.SFRBoxError: Failed to parse response: <?xml version="1.0" encoding="UTF-8"?><rsp stat="ok" version="1.0"><dsl linemode="G.DMT" uptime="4857" counter="1" crc="0" status="up" noise_down="4.5" noise_up="4.2" attenuation_down="3.2" attenuation_up="5.2" rate_down="8000" rate_up="800"
</firewall>
</rsp>
```

**Comment by epenet** [comment]
Wow! That seems to be a bug on the box: the return is not a valid XML!
It is mixing `dsl` element name and `firewall` element closure.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rsp stat="ok" version="1.0">
  <dsl linemode="G.DMT" uptime="4857" counter="1" crc="0" status="up" noise_down="4.5" noise_up="4.2" attenuation_down="3.2" attenuation_up="5.2" rate_down="8000" rate_up="800"
  </firewall>
</rsp>
```

**Comment by epenet** [comment]
Please try again with this workaround

**Comment by AlexT59** [comment]
Thanks for your fix, seems to work great !

But there is another error ^^

Here is the traceback:
```
INFO:httpx:HTTP Request: GET http://192.168.1.1/api/1.0/?method=ftth.getInfo "HTTP/1.1 200 Ok"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:sfrbox_api.bridge:HTTP Response: GET http://192.168.1.1/api/1.0/?method=ftth.getInfo "HTTP/1.1 200 Ok" <?xml version="1.0" encoding="UTF-8"?><rsp stat="ok" version="1.0"></rsp>

Traceback (most recent call last):
  File "/home/dev/GIT/sfrbox-api/src/example.py", line 33, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/dev/GIT/sfrbox-api/src/example.py", line 25, in main
    print(await box.ftth_get_info())
  File "/home/dev/GIT/sfrbox-api/src/sfrbox_api/bridge.py", line 179, in ftth_get_info
    xml_response = await self._send_get("ftth", "getInfo")
  File "/home/dev/GIT/sfrbox-api/src/sfrbox_api/bridge.py", line 52, in wrapper
    return await func(*args, **kwargs)
  File "/home/dev/GIT/sfrbox-api/src/sfrbox_api/bridge.py", line 152, in _send_get
    raise SFRBoxError(
sfrbox_api.exceptions.SFRBoxError: Namespace ftth not found in response: <?xml version="1.0" encoding="UTF-8"?><rsp stat="ok" version="1.0"></rsp>
```

**Comment by epenet** [comment]
New version ready to be tried again...

**Comment by AlexT59** [comment]
Seems ok, thanks

**Pull request merged**
